## NumPy
- 선형대수, 행렬 수치연산과 관련된 라이브러리
- NumPy 기반으로 통계, 머신러닝 등등 공부

In [ ]:
import numpy as np  # NumPy 라이브러리를 불러오기

print(np.__version__)

In [3]:
num1 = [1, 2, 3, 4]
num2 = [3, 4, 5, 6]

num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [4]:
arr1 = np.array(num1)
arr2 = np.array(num2)
arr1

array([1, 2, 3, 4])

In [5]:
arr2

array([3, 4, 5, 6])

In [6]:
arr1 + arr2

array([ 4,  6,  8, 10])

In [7]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [9]:
a1.dtype  # Python int  # NumPy int8, int16, int32, int64  => 메모리 관리

dtype('int32')

np.array([0.5, 2, 0.01, 8]).dtype

## NumPy 배열 생성
- 1차원, 2차원, 3차원... 배열 생성

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(10)  # 1차원 배열, 2차원 또는 3차원으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.arange(12).reshape(4, 5)

ValueError: cannot reshape array of size 12 into shape (4,5)

In [20]:
np.arange(12).reshape(4, 1, 3)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [21]:
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [23]:
b1 = np.arange(12).reshape(2, 2, 3)
b1.shape

(2, 2, 3)

In [25]:
b2 = np.arange(5)
b2.shape  # 1차원

(5,)

In [26]:
# 범위의 시작과 끝 정하기 배열 생성
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [28]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [29]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [32]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

## NumPy 기초 문법 배우는 이유
- 문과생: 데이터 분석가, 기초문법 있구나! 넘어가면 끝.
- 이공계: 수치연산, 배열, 수식 ==> 활용해서 문제 풀이
    + 클래스, 딥러닝 클래스, NumPy를 활용해서 딥러닝 알고리즘을 적용해서 클래스 & 라이브러리 만들기(이걸 프로젝트로)
    + 밑바닥부터 시작하는 딥러닝3 (책추천)

In [34]:
# 단위행렬
arr_I = np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
arr_I.shape

(3, 3)

In [36]:
np.array(['1.5', '0.62'])  # 데이터 형변환

array(['1.5', '0.62'], dtype='<U4')

In [37]:
# astype()  # pandas에서 사용가능
arr = np.array(['1.5', '0.62'])
num_arr = arr.astype(float)
num_arr.dtype

dtype('float64')

In [39]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(float)
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [40]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(int)
num_f1

array([10, 21,  0,  4,  5])

In [43]:
# p. 224
# 난수 무작위로 숫자를 추출한다

np.random.rand(2, 3)

array([[0.76546523, 0.53854228, 0.89399746],
       [0.61286979, 0.84701283, 0.65687528]])

In [47]:
np.random.randint(2, 3)  # 0 ~ 1 사이의 난수를 가짐

2

In [45]:
np.random.randint(2, 10)

6

In [46]:
np.random.randint(1, 100, 10)

array([25, 97, 42, 81, 68, 87, 20, 78, 95, 15])

In [52]:
# 로또 번호 생성기 만들기
np.random.randint(1, 46, 6)

array([27, 38,  2, 14, 13, 11])

In [63]:
# 번호가 겹치지 않는 로또 번호 생성기
lotto_numbers = []

while len(lotto_numbers) < 6:
    number = np.random.randint(1, 46)
    
    if number not in lotto_numbers:
        lotto_numbers.append(number)
        
# 숫자 순서대로 배열하기
print(sorted(lotto_numbers))

[6, 22, 25, 40, 42, 44]


In [56]:
selected_numbers = set()

while len (selected_numbers) < 6:
    selected_numbers.add(np.random.randint(1, 46))
    
print(sorted(selected_numbers))

[26, 33, 35, 38, 43, 44]
