In [1]:
import numpy as np
from matplotlib import pyplot as plt

from sklearn import tree
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [5]:
# 데이터 불러오기
iris = load_iris()
X = iris.data # 독립변수 가져오는 코드
y = iris.target # 종속변수 가져오는 코드

# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# 모델링
clf = DecisionTreeClassifier(max_depth=None, random_state=0)  # 디폴트 모델

# 모델 학습
clf.fit(X_train, y_train)

# 예측 데이터 생성
pred = clf.predict(X_test)
pred

# 평가지표
accuracy_score(y_test, pred)

0.9736842105263158

In [7]:
# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# 모델링
clf = DecisionTreeClassifier(max_depth=1, random_state=0)  # 디폴트 모델, max_depth 1로 변경

# 모델 학습
clf.fit(X_train, y_train)

# 예측 데이터 생성
pred = clf.predict(X_test)
pred

# 평가지표
accuracy_score(y_test, pred)

0.5789473684210527

In [12]:
# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# 모델링
clf = DecisionTreeClassifier(max_depth=2, random_state=0)  # 디폴트 모델, max_depth 2로 변경

# 모델 학습
clf.fit(X_train, y_train)

# 예측 데이터 생성
pred = clf.predict(X_test)
pred

# 평가지표
accuracy_score(y_test, pred)

0.8947368421052632

In [13]:
# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# 모델링
clf = DecisionTreeClassifier(max_depth=3, random_state=0)  # 디폴트 모델, max_depth 3으로 변경

# 모델 학습
clf.fit(X_train, y_train)

# 예측 데이터 생성
pred = clf.predict(X_test)
pred

# 평가지표
accuracy_score(y_test, pred)

0.9736842105263158

In [15]:
# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# 모델링
clf = DecisionTreeClassifier(max_depth=4, random_state=0)  # 디폴트 모델, max_depth 4로 변경

# 모델 학습
clf.fit(X_train, y_train)

# 예측 데이터 생성
pred = clf.predict(X_test)
pred

# 평가지표
accuracy_score(y_test, pred)

0.9736842105263158

## Grid Search vs Random Search 차이점, 최근 트렌드 동향
  + 베이지안 서치
  + https://hyperopt.github.io/hyperopt/ , https://optuna.org/ , https://scikit-optimize.github.io/stable/

In [18]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습데이타와 테스트 데이터 분리
iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

### 파라미터 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [22]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
### refit=True가 default임. True이면 가장 좋은 파라미터 설정으로 재학습시킴.
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 불꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [23]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.975000


In [25]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_
estimator

DecisionTreeClassifier(max_depth=3)

In [28]:
# GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667


## 데이터 전처리
- Feature Engineering

In [31]:
from sklearn.preprocessing import LabelEncoder

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

# LabelEncoder로 객체를 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
# 종속변수에 적용
# 수치 예측 할 때, LabelEncoder 사용 안함
# 범주 예측 : 예시, 양성 / 음성 / 잘 모르겠음

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 2 2]


In [32]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [33]:
encoder.inverse_transform([4, 5, 2])

array(['전자레인지', '컴퓨터', '믹서'], dtype='<U5')

## 원-핫 인코딩
- 문자를 숫자로 변경하는 것, Label Encoding과의 차이점

In [37]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 2차원 ndarray로 변환
items = np.array(items).reshape(-1,1)

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder로 변환한 결과는 희소행렬이므로 toarray()를 이용해 밀집 행렬로 변환
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [38]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

## 피처 스케일링과 정규화
- 기본값으로 무조건 사용
 + ML 알고리즘 상관없이, 디폴트로 사용하자
- 수치 데이터, 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업
 + 판매 데이터
   - 광고투입비용, 온도, 시간, 판매량, 매출액 등
- 만약, 트리 계열 알고리즘
 + 굳이 스케일링과 정규화가 필요가 없음
- SVM, KNN, 베이지안, 회귀 등 다양한 알고리즘 사용
 + 꼭 활용

In [39]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다.
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


### StandardScaler 객체 생성
- 각 피처, 수치형 컬럼, 한 번에 표준화를 해보겠다!

In [41]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터 세트 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터세트가 NumPy ndarray로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균 값')
print(iris_df_scaled.mean())
print('featrue들의 분산 값')
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
featrue들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


## MinMaxScaler
- 수치 데이터를 0과 1 사이의 범위 값으로 변환
  + 만약에, 음수가 존재하면 -1에서 1값으로 변환


In [44]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()
# MinMaxScaler로 데이터 세트 변환. fit()과 transform() 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 스케일 변환된 데이터 세트가 NumPy ndarray로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('feature들의 최댓값')
print(iris_df_scaled.max())


feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
